=== albertalvin8080/Learning-XML/IFPE-LDD/Exercicios_de_Fixacao/ex03-13-14/bibliography.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bibliography">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="lang" type="xs:string"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="author" minOccurs="1" maxOccurs="unbounded" type="xs:string"></xs:element>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[1-9]\d{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price" type="xs:decimal"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="category" type="xs:string" default="LP"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== albertalvin8080/Learning-XML/IFPE-LDD/Exercicios_de_Fixacao/ex03-13-14/bibliography.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliography xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bibliography.xsd">
    <book category="LP">
        <title lang="pt-br">C: Como Programar</title>
        <author>Paul Deitel</author>
        <author>Harvey Deitel</author>
        <year>2011</year>
        <price>220.00</price>
    </book>
    <book category="AC">
        <title lang="pt-br">Organização Estruturada de Computadores</title>
        <author>Andrew S. Tanenbaum</author>
        <year>2006</year>
        <price>166.90</price>
    </book>
    <book category="BD">
        <title lang="pt-br">Sistemas de Banco de Dados</title>
        <author>Abraham Silberschatz</author>
        <author>Henry F. Korth</author>
        <author>S. Sudarshan</author>
        <year>2012</year>
        <price>180.90</price>
    </book>
    <book category="ES">
        <title lang="pt-br">Engenharia de Software</title>
        <author>Roger S. Pressman</author>
        <year>2011</year>
        <price>137.90</price>
    </book>
    <book category="LP">
        <title lang="en">Beginning XML</title>
        <author>Joe Fawcett</author>
        <author>Danny Ayers</author>
        <author>Liam R. E. Quin</author>
        <year>2012</year>
        <price>26.25</price>
    </book>
    <book category="RC">
        <title lang="en">Computer Networking: A Top-Down Approach</title>
        <author>James F. Kurose</author>
        <author>Keith W. Ross</author>
        <year>2012</year>
        <price>122.17</price>
    </book>
    <book category="LP">
        <title lang="en">Head First Servlets and JSP: Passing the Sun Certified Web Component Developed Exam</title>
        <author>Kathy Sierra</author>
        <author>Bert Bates</author>
        <year>2008</year>
        <price>30.64</price>
    </book>
    <book category="ES">
        <title lang="pt-br">Utilizando UML e Padrões: Uma Introdução à Análise e Projeto Orientados a Objetos e ao Processo Unificado</title>
        <author>Craig Larman</author>
        <year>2007</year>
        <price>166.00</price>
    </book>
    <book category="SO">
        <title lang="en">Operating System Concepts</title>
        <author>Abraham Silberschatz</author>
        <author>Peter B. Galvin</author>
        <author>Greg Gagne</author>
        <year>2012</year>
        <price>130.48</price>
    </book>
    <book category="ES">
        <title lang="en">Software Testing</title>
        <author>Ron Patton</author>
        <year>2005</year>
        <price>25.99</price>
    </book>
    <book category="IA">
        <title lang="en">Artificial Intelligence: A Modern Approach</title>
        <author>Stuart Russell</author>
        <author>Peter Norvig</author>
        <year>2009</year>
        <price>137.92</price>
    </book>
    <book category="SO">
        <title lang="pt-br">Sistemas Operacionais Modernos</title>
        <author>Andrew S. Tanenbaum</author>
        <year>2010</year>
        <price>138.00</price>
    </book>
    <book category="LP">
        <title lang="en">XSLT</title>
        <author>Doug Tidwell</author>
        <year>2008</year>
        <price>46.68</price>
    </book>
</bibliography>
